#!/usr/bin/env python3
"""Validate generated RDF files before Zenodo upload.

Three levels of checks are performed:

1. Individual TTL files in output/rdf/  — RDFlib syntax parse of every file
   generated by the Java converter and the plugin scripts.  Each file is
   small so this is fast and catches converter output errors precisely.

2. Extra bundles (taxonomy, properties) — RDFlib parse of the aggregated
   files, plus content checks for required predicates and minimum triple
   counts.  The taxonomy bundle is small (~2 MB) and fully parsed.  The
   properties bundle is larger (~160 MB) so only a line-scan is done for
   expected patterns.

3. Core bundle and VoID — size check + line-scan for expected patterns
   on the large core file (274 MB+), and a full RDFlib parse of the small
   VoID file with a check that at least three void:Dataset instances exist.

Run locally after the full pipeline, before uploading to Zenodo:

    python scripts/validate_rdf.py

Use --skip-individual to skip per-file parsing (used in CI to save time):

    python scripts/validate_rdf.py --skip-individual
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from rdflib import Graph, Namespace, RDF
from tqdm import tqdm

WP = Namespace("http://vocabularies.wikipathways.org/wp#")
PMW = Namespace("http://rdf-plantmetwiki.bioinformatics.nl/vocab/")
VOID_NS = Namespace("http://rdfs.org/ns/void#")
NCBI = Namespace("http://purl.obolibrary.org/obo/NCBITaxon_")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_version(metadata_path: Path) -> str:
    return json.loads(metadata_path.read_text(encoding="utf-8"))["version"]


def parse_ttl(path: Path) -> tuple[Graph | None, str]:
    """Parse a Turtle file with RDFlib. Returns (graph, error_message)."""
    try:
        g = Graph()
        g.parse(path, format="turtle")
        return g, ""
    except Exception as exc:
        return None, str(exc)


def file_contains(path: Path, pattern: str) -> bool:
    """Scan a file line by line for a string pattern (memory efficient)."""
    with path.open(encoding="utf-8", errors="replace") as fh:
        for line in fh:
            if pattern in line:
                return True
    return False


def result(label: str, errors: list[str], note: str = "") -> bool:
    status = "PASS" if not errors else "FAIL"
    suffix = f"  ({note})" if note else ""
    print(f"  [{status}] {label}{suffix}")
    for err in errors:
        print(f"         ↳ {err}")
    return not errors


# ---------------------------------------------------------------------------
# Validators
# ---------------------------------------------------------------------------

def validate_individual_ttls(rdf_dir: Path) -> tuple[int, int, list[str]]:
    """RDFlib syntax-parse every TTL file under rdf_dir recursively."""
    passed = failed = 0
    errors: list[str] = []

    ttl_files = sorted(rdf_dir.rglob("*.ttl"))
    for ttl in tqdm(ttl_files, desc=f"    {rdf_dir}", leave=False):
        _, err = parse_ttl(ttl)
        if err:
            failed += 1
            errors.append(f"{ttl.name}: {err}")
        else:
            passed += 1

    return passed, failed, errors


def validate_taxonomy_bundle(path: Path) -> list[str]:
    """Full RDFlib parse + content checks on the taxonomy-extra bundle (~2 MB)."""
    errors: list[str] = []
    if not path.exists():
        return [f"Missing file: {path}"]

    g, err = parse_ttl(path)
    if err:
        return [f"Parse error: {err}"]

    triple_count = len(g)
    if triple_count < 1_000:
        errors.append(f"Only {triple_count} triples (expected >= 1 000)")

    viridiplantae = NCBI["33090"]
    if not any(True for _ in g.triples((None, WP.organism, viridiplantae))):
        errors.append("No wp:organism ncbi:33090 (Viridiplantae) triples found")

    return errors


def validate_large_bundle(
    path: Path,
    min_size_mb: float,
    required_patterns: list[str],
) -> list[str]:
    """Validate a large bundle by file size and line-scanning for patterns."""
    errors: list[str] = []
    if not path.exists():
        return [f"Missing file: {path}"]

    size_mb = path.stat().st_size / (1024 * 1024)
    if size_mb < min_size_mb:
        errors.append(
            f"File is {size_mb:.1f} MB — expected >= {min_size_mb} MB"
            " (may indicate an incomplete build)"
        )

    for pattern in required_patterns:
        if not file_contains(path, pattern):
            errors.append(f"Expected pattern not found: {pattern!r}")

    return errors


def validate_prefix_uniqueness(path: Path) -> list[str]:
    """Check that no @prefix declaration is repeated in a bundle file."""
    errors: list[str] = []
    counts: dict[str, int] = {}
    with path.open(encoding="utf-8", errors="replace") as fh:
        for line in fh:
            stripped = line.strip()
            if stripped.startswith("@prefix"):
                parts = stripped.split()
                if len(parts) >= 2:
                    key = parts[1]
                    counts[key] = counts.get(key, 0) + 1

    duplicates = {k: v for k, v in counts.items() if v > 1}
    for prefix, count in sorted(duplicates.items()):
        errors.append(f"@prefix {prefix} declared {count} times")
    return errors


def validate_void(path: Path) -> list[str]:
    """Full RDFlib parse of the VoID file + structural check."""
    errors: list[str] = []
    if not path.exists():
        return [f"Missing file: {path}"]

    g, err = parse_ttl(path)
    if err:
        return [f"Parse error: {err}"]

    datasets = list(g.subjects(RDF.type, VOID_NS.Dataset))
    if len(datasets) < 3:
        errors.append(
            f"Found {len(datasets)} void:Dataset instance(s) — expected >= 3"
            " (core, taxonomy-extra, properties-extra)"
        )

    return errors


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate RDF bundles before Zenodo upload."
    )
    parser.add_argument(
        "--version",
        default=None,
        help="Version string (auto-read from build/zenodo_gpml_metadata.json if omitted)",
    )
    parser.add_argument(
        "--metadata-file",
        default="build/zenodo_gpml_metadata.json",
    )
    parser.add_argument("--rdf-dir", default="output/rdf")
    parser.add_argument("--bundles-dir", default="output/bundles")
    parser.add_argument(
        "--skip-individual",
        action="store_true",
        help="Skip per-file TTL syntax validation (used in CI to save time)",
    )
    args = parser.parse_args()

    version = args.version or load_version(Path(args.metadata_file))
    bundles = Path(args.bundles_dir)
    rdf_dir = Path(args.rdf_dir)

    print(f"Validating RDF — version: {version}\n")
    all_passed = True

    # ------------------------------------------------------------------
    # 1. Individual TTL files — syntax check via RDFlib
    # ------------------------------------------------------------------
    if not args.skip_individual:
        print("=== Individual TTL files (syntax) ===")
        passed, failed, errors = validate_individual_ttls(rdf_dir)
        all_passed &= result(
            str(rdf_dir),
            errors,
            note=f"{passed} OK, {failed} failed",
        )
        print()

    # ------------------------------------------------------------------
    # 2 & 3. Bundle files
    # ------------------------------------------------------------------
    print("=== Bundle files ===")

    taxonomy_bundle = bundles / f"all_gpml_taxonomy_extra-{version}.ttl"
    properties_bundle = bundles / f"all_gpml_properties_extra-{version}.ttl"
    core_bundle = bundles / f"all-{version}.ttl"
    void_file = bundles / f"void-{version}.ttl"

    # Taxonomy extra — small enough for full RDFlib parse
    errors = validate_taxonomy_bundle(taxonomy_bundle)
    all_passed &= result("taxonomy-extra bundle (RDFlib)", errors)

    errors = validate_prefix_uniqueness(taxonomy_bundle)
    all_passed &= result("taxonomy-extra bundle (prefix uniqueness)", errors)

    # Properties extra — large, use size + pattern scan
    errors = validate_large_bundle(
        properties_bundle,
        min_size_mb=50,
        required_patterns=["pmw:gpmlProperty", "pmw:key"],
    )
    all_passed &= result("properties-extra bundle (size + patterns)", errors)

    if properties_bundle.exists():
        errors = validate_prefix_uniqueness(properties_bundle)
        all_passed &= result("properties-extra bundle (prefix uniqueness)", errors)

    # Core bundle — large, use size + pattern scan
    errors = validate_large_bundle(
        core_bundle,
        min_size_mb=100,
        required_patterns=[
            "wp:organism",
            "rdf-plantmetwiki.bioinformatics.nl/pathways/",
        ],
    )
    all_passed &= result("core bundle (size + patterns)", errors)

    if core_bundle.exists():
        errors = validate_prefix_uniqueness(core_bundle)
        all_passed &= result("core bundle (prefix uniqueness)", errors)

    # VoID — small, full RDFlib parse
    errors = validate_void(void_file)
    all_passed &= result("void file (RDFlib)", errors)

    # ------------------------------------------------------------------
    print()
    if all_passed:
        print("✅ All checks passed — safe to upload to Zenodo")
        return 0
    else:
        print("❌ Validation failed — fix errors before uploading to Zenodo")
        return 1


if __name__ == "__main__":
    sys.exit(main())
